apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: like
  namespace: blog
spec:
  route:
    filters:
    - SetRequestHeader=Host, like.apps.pcfone.io
    - SetResponseHeader=Access-Control-Allow-Origin, *
    - SetResponseHeader=Access-Control-Allow-Methods, GET, OPTIONS
    - SetResponseHeader=Access-Control-Max-Age, 3600
    - SetResponseHeader=Access-Control-Allow-Headers, *
    - RequestLogging=
    - name: Retry
      args:
        retries: "3"
        statuses: BAD_GATEWAY,NOT_FOUND
    predicates:
    - Host=like.dev.ik.am
    uri: https://like.apps.pcfone.io:443
